<?php

$filtershow = "All Campaigns";
if ($campid) $filtershow = "Campaign ".$pages_array[$campid];
##### START THIS STAT REPORT AND PRINT OUT THE
##### CAMPAIGN/DATE FILTER FORM

echo "<font class=stats_header>Summary</font><br><font class=stats_subheader>$filtershow<br>$filtershow2</font><p>";
include "includes/filterform2.php";
if (!$gshits&&!$gsclicks&&!$gsvisitors&&!$gsrvisitors&&!$gsvisits) $gsall = 1;
if (!$dow&&!$dom&&!$mon&&!$yea) $dow = 1;
if ($gsall) {	$gshits = 1;
	$gsclicks = 1;
	$gsvisits = 1;
	$gsvisitors = 1;
 	$gsrvisitors = 1;
 }if ($campid) $filter2 = "and pageid='$campid' $filter2";
$c = mysql_query("select id from $statstableprefix"."_".$id." where id!='0' $filter2 limit 1");
$d = mysql_fetch_object($c);
#########################################

if ($d->id) {echo "<hr><br>";
##### CREATE THE ARRAYS OF GRAPH INFORMATION

$echolater = "<table class=showstats width=100%>";
$c = mysql_query("select * from $statstableprefix"."_".$id."_old where id>='1' $filter2");
while ($d = mysql_fetch_object($c)) {	$dy = date("D",$d->time);
	$dt = date("d",$d->time);
	$m = date("m",$d->time);
	$y = date("Y",$d->time);
			$day_array_h[$dy] += $d->hits;
		$date_array_h[$dt] += $d->hits;
		$month_array_h[$m] += $d->hits;
		$year_array_h[$y] += $d->hits;
		$day_array_c[$dy] += $d->clicks;
		$date_array_c[$dt] += $d->clicks;
		$month_array_c[$m] += $d->clicks;
		$year_array_c[$y] += $d->clicks;
		$day_array_v2[$dy] += $d->visitors;
		$date_array_v2[$dt] += $d->visitors;
		$month_array_v2[$m] += $d->visitors;
				$year_array_v2[$y] += $d->visitors;
		$day_array_v3[$dy] += $d->rv;
		$date_array_v3[$dt] += $d->rv;
		$month_array_v3[$m] += $d->rv;
				$year_array_v3[$y] += $d->rv;
 }for($i=1;
$i<=31;
$i++) {	if (strlen($i) <= 1) $i = "0$i";
	if (!$date_array_h[$i]) $date_array_h[$i] = "0";
	if (!$date_array_c[$i]) $date_array_c[$i] = "0";
	if (!$date_array_v[$i]) $date_array_v[$i] = "0";
	if (!$date_array_v2[$i]) $date_array_v2[$i] = "0";
	if (!$date_array_v3[$i]) $date_array_v3[$i] = "0";
 }for($i=1;
$i<=12;
$i++) {	if (strlen($i) <= 1) $i = "0$i";
	if (!$month_array_h[$i]) $month_array_h[$i] = "0";
	if (!$month_array_c[$i]) $month_array_c[$i] = "0";
	if (!$month_array_v[$i]) $month_array_v[$i] = "0";
	if (!$month_array_v2[$i]) $month_array_v2[$i] = "0";
	if (!$month_array_v3[$i]) $month_array_v3[$i] = "0";
 }ksort($date_array_h);
ksort($month_array_h);
ksort($year_array_h);
ksort($date_array_c);
ksort($month_array_c);
ksort($year_array_c);
ksort($date_array_v2);
ksort($month_array_v2);
ksort($year_array_v2);
ksort($date_array_v3);
ksort($month_array_v3);
ksort($year_array_v3);
if (!$day_array_h['Sun']) $day_array_h['Sun'] = "0";
if (!$day_array_c['Sun']) $day_array_c['Sun'] = "0";
if (!$day_array_h['Mon']) $day_array_h['Mon'] = "0";
if (!$day_array_c['Mon']) $day_array_c['Mon'] = "0";
if (!$day_array_h['Tue']) $day_array_h['Tue'] = "0";
if (!$day_array_c['Tue']) $day_array_c['Tue'] = "0";
if (!$day_array_h['Wed']) $day_array_h['Wed'] = "0";
if (!$day_array_c['Wed']) $day_array_c['Wed'] = "0";
if (!$day_array_h['Thu']) $day_array_h['Thu'] = "0";
if (!$day_array_c['Thu']) $day_array_c['Thu'] = "0";
if (!$day_array_h['Fri']) $day_array_h['Fri'] = "0";
if (!$day_array_c['Fri']) $day_array_c['Fri'] = "0";
if (!$day_array_h['Sat']) $day_array_h['Sat'] = "0";
if (!$day_array_c['Sat']) $day_array_c['Sat'] = "0";
$new_day_array_h['Sun'] = $day_array_h['Sun'];
$new_day_array_c['Sun'] = $day_array_c['Sun'];
$new_day_array_h['Mon'] = $day_array_h['Mon'];
$new_day_array_c['Mon'] = $day_array_c['Mon'];
$new_day_array_h['Tue'] = $day_array_h['Tue'];
$new_day_array_c['Tue'] = $day_array_c['Tue'];
$new_day_array_h['Wed'] = $day_array_h['Wed'];
$new_day_array_c['Wed'] = $day_array_c['Wed'];
$new_day_array_h['Thu'] = $day_array_h['Thu'];
$new_day_array_c['Thu'] = $day_array_c['Thu'];
$new_day_array_h['Fri'] = $day_array_h['Fri'];
$new_day_array_c['Fri'] = $day_array_c['Fri'];
$new_day_array_h['Sat'] = $day_array_h['Sat'];
$new_day_array_c['Sat'] = $day_array_c['Sat'];
if (!$day_array_v['Sun']) $day_array_v['Sun'] = "0";
if (!$day_array_v2['Sun']) $day_array_v2['Sun'] = "0";
if (!$day_array_v['Mon']) $day_array_v['Mon'] = "0";
if (!$day_array_v2['Mon']) $day_array_v2['Mon'] = "0";
if (!$day_array_v['Tue']) $day_array_v['Tue'] = "0";
if (!$day_array_v2['Tue']) $day_array_v2['Tue'] = "0";
if (!$day_array_v['Wed']) $day_array_v['Wed'] = "0";
if (!$day_array_v2['Wed']) $day_array_v2['Wed'] = "0";
if (!$day_array_v['Thu']) $day_array_v['Thu'] = "0";
if (!$day_array_v2['Thu']) $day_array_v2['Thu'] = "0";
if (!$day_array_v['Fri']) $day_array_v['Fri'] = "0";
if (!$day_array_v2['Fri']) $day_array_v2['Fri'] = "0";
if (!$day_array_v['Sat']) $day_array_v['Sat'] = "0";
if (!$day_array_v2['Sat']) $day_array_v2['Sat'] = "0";
$new_day_array_v['Sun'] = $day_array_v['Sun'];
$new_day_array_v2['Sun'] = $day_array_v2['Sun'];
$new_day_array_v['Mon'] = $day_array_v['Mon'];
$new_day_array_v2['Mon'] = $day_array_v2['Mon'];
$new_day_array_v['Tue'] = $day_array_v['Tue'];
$new_day_array_v2['Tue'] = $day_array_v2['Tue'];
$new_day_array_v['Wed'] = $day_array_v['Wed'];
$new_day_array_v2['Wed'] = $day_array_v2['Wed'];
$new_day_array_v['Thu'] = $day_array_v['Thu'];
$new_day_array_v2['Thu'] = $day_array_v2['Thu'];
$new_day_array_v['Fri'] = $day_array_v['Fri'];
$new_day_array_v2['Fri'] = $day_array_v2['Fri'];
$new_day_array_v['Sat'] = $day_array_v['Sat'];
$new_day_array_v2['Sat'] = $day_array_v2['Sat'];
if (!$day_array_v3['Sun']) $day_array_v3['Sun'] = "0";
if (!$day_array_v3['Mon']) $day_array_v3['Mon'] = "0";
if (!$day_array_v3['Tue']) $day_array_v3['Tue'] = "0";
if (!$day_array_v3['Wed']) $day_array_v3['Wed'] = "0";
if (!$day_array_v3['Thu']) $day_array_v3['Thu'] = "0";
if (!$day_array_v3['Fri']) $day_array_v3['Fri'] = "0";
if (!$day_array_v3['Sat']) $day_array_v3['Sat'] = "0";
$new_day_array_v3['Sun'] = $day_array_v3['Sun'];
$new_day_array_v3['Mon'] = $day_array_v3['Mon'];
$new_day_array_v3['Tue'] = $day_array_v3['Tue'];
$new_day_array_v3['Wed'] = $day_array_v3['Wed'];
$new_day_array_v3['Thu'] = $day_array_v3['Thu'];
$new_day_array_v3['Fri'] = $day_array_v3['Fri'];
$new_day_array_v3['Sat'] = $day_array_v3['Sat'];
if ($dow) {$graph_data1 = "";
$graph_data2 = "";
$graph_data3 = "";
$graph_data4 = "";
$graph_data5 = "";
$graph_legends = "";
if ($new_day_array_h) {	foreach ($new_day_array_h as $key=>$value) {		$graph_data1 .= $value.",";
		$graph_data2 .= $new_day_array_c[$key].",";
		$graph_data3 .= $new_day_array_v[$key].",";
		$graph_data4 .= $new_day_array_v2[$key].",";
		$graph_data5 .= $new_day_array_v3[$key].",";
		$graph_legends .= $key.",";
 } }$graph_data1 = trim($graph_data1, "\,");
$graph_data2 = trim($graph_data2, "\,");
$graph_data3 = trim($graph_data3, "\,");
$graph_data4 = trim($graph_data4, "\,");
$graph_data5 = trim($graph_data5, "\,");
$graph_legends = trim($graph_legends, "\,");
$gls = explode(",",$graph_legends);
$gd1 = explode(",",$graph_data1);
$gd2 = explode(",",$graph_data2);
$gd3 = explode(",",$graph_data3);
$gd4 = explode(",",$graph_data4);
$gd5 = explode(",",$graph_data5);

$echolater = "<table cellpadding=3 border=1 width=100% style=\"border-color:#8c8c8c;
border-style:solid;
border-width:1px;
border-collapse:collapse;
\"><tr><td>&nbsp;
</td><td width=19%><b>Pageloads</b></td><td width=19%><b>Clicks</b></td><td width=19%><b>Unique Visitors</b></td><td width=19%><b>Return Visitors</b></td></tr>";
$cvfd = 0;
foreach ($gd1 as $i) {	$echolater .= "<tr><td><b>$gls[$cvfd]</b></td><td>$gd1[$cvfd]</td><td>$gd2[$cvfd]</td><td>$gd4[$cvfd]</td><td>$gd5[$cvfd]</td></tr>";
	$cvfd++;
	$t1 += $gd1[$cvfd];
	$t2 += $gd2[$cvfd];
	$t4 += $gd4[$cvfd];
	$t5 += $gd5[$cvfd];
 }
$echolater .= "<tr><td><b>Totals:</b></td><td><b>$t1</b></td><td><b>$t2</b></td><td><b>$t4</b></td><td><b>$t5</b></td></tr>";
$echolater .= "</table>";
if (!$gshits) $graph_data1 = "";
if (!$gsclicks) $graph_data2 = "";
if (!$gsvisits) $graph_data3 = "";
if (!$gsvisitors) $graph_data4 = "";
if (!$gsrvisitors) $graph_data5 = "";
echo "<br><font class=stats_subheader>Pageloads, Clicks, Unique Visitors, Return Visitors</font><br><br><img src=\"graph1.php?grace=1&jptitle=Pageloads, Clicks, Unique Visitors, Return Visitors&jplegends=$graph_legends&jpdata1=$graph_data1&jpdata2=$graph_data2&jpdata4=$graph_data4&jpdata5=$graph_data5&jpl1=Pageloads&jpl2=Clicks&jpl4=Unique Visitors&jpl5=Return Visitors\"><br> <br><br>$echolater";
}if ($dom) {$graph_data1 = "";
$graph_data2 = "";
$graph_data3 = "";
$graph_data4 = "";
$graph_data5 = "";
$graph_legends = "";
if ($date_array_h) {	foreach ($date_array_h as $key=>$value) {		$graph_data1 .= $value.",";
		$graph_data2 .= $date_array_c[$key].",";
		$graph_data3 .= $date_array_v[$key].",";
		$graph_data4 .= $date_array_v2[$key].",";
		$graph_data5 .= $date_array_v3[$key].",";
		$graph_legends .= $key.",";
 } }$graph_data1 = trim($graph_data1, "\,");
$graph_data2 = trim($graph_data2, "\,");
$graph_data3 = trim($graph_data3, "\,");
$graph_data4 = trim($graph_data4, "\,");
$graph_data5 = trim($graph_data5, "\,");
$graph_legends = trim($graph_legends, "\,");
$gls = explode(",",$graph_legends);
$gd1 = explode(",",$graph_data1);
$gd2 = explode(",",$graph_data2);
$gd3 = explode(",",$graph_data3);
$gd4 = explode(",",$graph_data4);
$gd5 = explode(",",$graph_data5);
$echolater = "<table cellpadding=3 border=1 width=100% style=\"border-color:#8c8c8c;
border-style:solid;
border-width:1px;
border-collapse:collapse;
\"><tr><td>&nbsp;
</td><td width=19%>Pageloads</td><td width=19%>Clicks</td><td width=19%>Unique Visitors</td><td width=19%>Return Visitors</td></tr>";
$cvfd = 0;
foreach ($gd1 as $i) {	$echolater .= "<tr><td>Day $gls[$cvfd]</td><td>$gd1[$cvfd]</td><td>$gd2[$cvfd]</td><td>$gd4[$cvfd]</td><td>$gd5[$cvfd]</td></tr>";
	$cvfd++;
	$t1 += $gd1[$cvfd];
	$t2 += $gd2[$cvfd];
	$t4 += $gd4[$cvfd];
	$t5 += $gd5[$cvfd];
 }
$echolater .= "<tr><td><b>Totals:</b></td><td><b>$t1</b></td><td><b>$t2</b></td><td><b>$t4</b></td><td><b>$t5</b></td></tr>";
$echolater .= "</table>";
if (!$gshits) $graph_data1 = "";
if (!$gsclicks) $graph_data2 = "";
if (!$gsvisits) $graph_data3 = "";
if (!$gsvisitors) $graph_data4 = "";
if (!$gsrvisitors) $graph_data5 = "";
echo "<br><font class=stats_subheader>Pageloads, Clicks, Unique Visitors, Return Visitors</font><br><br><img src=\"graph1.php?novalues=1&jptitle=Pageloads, Clicks, Unique Visitors, Return Visitors&jplegends=$graph_legends&jpdata1=$graph_data1&jpdata2=$graph_data2&jpdata4=$graph_data4&jpdata5=$graph_data5&jpl1=Pageloads&jpl2=Clicks&jpl4=Unique Visitors&jpl5=Return Visitors\"><br> <br><br>$echolater";
}if ($mon) {$graph_data1 = "";
$graph_data2 = "";
$graph_data3 = "";
$graph_data4 = "";
$graph_data5 = "";
$graph_legends = "";
if ($month_array_h) {	foreach ($month_array_h as $key=>$value) {		$graph_data1 .= $value.",";
		$graph_data2 .= $month_array_c[$key].",";
		$graph_data3 .= $month_array_v[$key].",";
		$graph_data4 .= $month_array_v2[$key].",";
		$graph_data5 .= $month_array_v3[$key].",";
		$graph_legends .= $key.",";
 } }$graph_data1 = trim($graph_data1, "\,");
$graph_data2 = trim($graph_data2, "\,");
$graph_data3 = trim($graph_data3, "\,");
$graph_data4 = trim($graph_data4, "\,");
$graph_data5 = trim($graph_data5, "\,");
$graph_legends = trim($graph_legends, "\,");
$gls = explode(",",$graph_legends);
$gd1 = explode(",",$graph_data1);
$gd2 = explode(",",$graph_data2);
$gd3 = explode(",",$graph_data3);
$gd4 = explode(",",$graph_data4);
$gd5 = explode(",",$graph_data5);
$echolater = "<table cellpadding=3 border=1 width=100% style=\"border-color:#8c8c8c;
border-style:solid;
border-width:1px;
border-collapse:collapse;
\"><tr><td>&nbsp;
</td><td width=19%>Pageloads</td><td width=19%>Clicks</td><td width=19%>Unique Visitors</td><td width=19%>Return Visitors</td></tr>";
$cvfd = 0;
foreach ($gd1 as $i) {	$echolater .= "<tr><td>Month $gls[$cvfd]</td><td>$gd1[$cvfd]</td><td>$gd2[$cvfd]</td><td>$gd4[$cvfd]</td><td>$gd5[$cvfd]</td></tr>";
	$cvfd++;
	$t1 += $gd1[$cvfd];
	$t2 += $gd2[$cvfd];
	$t4 += $gd4[$cvfd];
	$t5 += $gd5[$cvfd];
 }
$echolater .= "<tr><td><b>Totals:</b></td><td><b>$t1</b></td><td><b>$t2</b></td><td><b>$t4</b></td><td><b>$t5</b></td></tr>";
$echolater .= "</table>";
if (!$gshits) $graph_data1 = "";
if (!$gsclicks) $graph_data2 = "";
if (!$gsvisits) $graph_data3 = "";
if (!$gsvisitors) $graph_data4 = "";
if (!$gsrvisitors) $graph_data5 = "";
echo "<br><font class=stats_subheader>Pageloads, Clicks, Unique Visitors, Return Visitors</font><br><br><img src=\"graph1.php?grace=1&jptitle=Pageloads, Clicks, Unique Visitors, Return Visitors&jplegends=$graph_legends&jpdata1=$graph_data1&jpdata2=$graph_data2&jpdata4=$graph_data4&jpdata5=$graph_data5&jpl1=Pageloads&jpl2=Clicks&jpl4=Unique Visitors&jpl5=Return Visitors\"><br> <br><br>$echolater";
}if ($yea) {$graph_data1 = "";
$graph_data2 = "";
$graph_data3 = "";
$graph_data4 = "";
$graph_data5 = "";
$graph_legends = "";
if ($year_array_h) {	foreach ($year_array_h as $key=>$value) {		$graph_data1 .= $value.",";
		$graph_data2 .= $year_array_c[$key].",";
		$graph_data3 .= $year_array_v[$key].",";
		$graph_data4 .= $year_array_v2[$key].",";
		$graph_data5 .= $year_array_v3[$key].",";
		$graph_legends .= $key.",";
 } }$graph_data1 = trim($graph_data1, "\,");
$graph_data2 = trim($graph_data2, "\,");
$graph_data3 = trim($graph_data3, "\,");
$graph_data4 = trim($graph_data4, "\,");
$graph_data5 = trim($graph_data5, "\,");
$graph_legends = trim($graph_legends, "\,");
$gls = explode(",",$graph_legends);
$gd1 = explode(",",$graph_data1);
$gd2 = explode(",",$graph_data2);
$gd3 = explode(",",$graph_data3);
$gd4 = explode(",",$graph_data4);
$gd5 = explode(",",$graph_data5);
$echolater = "<table cellpadding=3 border=1 width=100% style=\"border-color:#8c8c8c;
border-style:solid;
border-width:1px;
border-collapse:collapse;
\"><tr><td>&nbsp;
</td><td width=19%>Pageloads</td><td width=19%>Clicks</td><td width=19%>Unique Visitors</td><td width=19%>Return Visitors</td></tr>";
$cvfd = 0;
foreach ($gd1 as $i) {	$echolater .= "<tr><td>$gls[$cvfd]</td><td>$gd1[$cvfd]</td><td>$gd2[$cvfd]</td><td>$gd4[$cvfd]</td><td>$gd5[$cvfd]</td></tr>";
	$cvfd++;
	$t1 += $gd1[$cvfd];
	$t2 += $gd2[$cvfd];
	$t4 += $gd4[$cvfd];
	$t5 += $gd5[$cvfd];
 }
$echolater .= "<tr><td><b>Totals:</b></td><td><b>$t1</b></td><td><b>$t2</b></td><td><b>$t4</b></td><td><b>$t5</b></td></tr>";
$echolater .= "</table>";
if (!$gshits) $graph_data1 = "";
if (!$gsclicks) $graph_data2 = "";
if (!$gsvisits) $graph_data3 = "";
if (!$gsvisitors) $graph_data4 = "";
if (!$gsrvisitors) $graph_data5 = "";
echo "<br><font class=stats_subheader>Pageloads, Clicks, Unique Visitors, Return Visitors</font><br><br><img src=\"graph1.php?grace=1&jptitle=Pageloads, Clicks, Unique Visitors, Return Visitors&jplegends=$graph_legends&jpdata1=$graph_data1&jpdata2=$graph_data2&jpdata4=$graph_data4&jpdata5=$graph_data5&jpl1=Pageloads&jpl2=Clicks&jpl4=Unique Visitors&jpl5=Return Visitors\"><br> <br><br>$echolater";
}}else {	echo "No Records Found!";
 }?>